config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :advisors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'students#index'
end

app/models/advisor.rb
class Advisor < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  before_action :set_advisor, only: [:show, :edit, :update, :destroy]

  # GET /advisors
  # GET /advisors.json
  def index
    @advisors = Advisor.all
  end

  # GET /advisors/1
  # GET /advisors/1.json
  def show
  end

  # GET /advisors/new
  def new
    @advisor = Advisor.new
  end

  # GET /advisors/1/edit
  def edit
  end

  # POST /advisors
  # POST /advisors.json
  def create
    @advisor = Advisor.new(advisor_params)

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to @advisor, notice: 'Advisor was successfully created.' }
        format.json { render :show, status: :created, location: @advisor }
      else
        format.html { render :new }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advisors/1
  # PATCH/PUT /advisors/1.json
  def update
    respond_to do |format|
      if @advisor.update(advisor_params)
        format.html { redirect_to @advisor, notice: 'Advisor was successfully updated.' }
        format.json { render :show, status: :ok, location: @advisor }
      else
        format.html { render :edit }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1
  # DELETE /advisors/1.json
  def destroy
    @advisor.destroy
    respond_to do |format|
      format.html { redirect_to advisors_url, notice: 'Advisor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advisor
      @advisor = Advisor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advisor_params
      params.require(:advisor).permit(:advisorid, :firstname, :lastname, :email, :student_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:csuid, :firstname, :lastname, :email)
    end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/advisors/_form.html.erb
<%= form_with(model: advisor, local: true) do |form| %>
  <% if advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% advisor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :advisorid %>
    <%= form.number_field :advisorid, id: :advisor_advisorid %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :advisor_firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :advisor_lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :advisor_email %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id, id: :advisor_student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advisors/edit.html.erb
<h1>Editing Advisor</h1>

<%= render 'form', advisor: @advisor %>

<%= link_to 'Show', @advisor %> |
<%= link_to 'Back', advisors_path %>

app/views/advisors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advisors</h1>

<table>
  <thead>
    <tr>
      <th>Advisorid</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advisors.each do |advisor| %>
      <tr>
        <td><%= advisor.advisorid %></td>
        <td><%= advisor.firstname %></td>
        <td><%= advisor.lastname %></td>
        <td><%= advisor.email %></td>
        <td><%= advisor.student_id %></td>
        <td><%= link_to 'Show', advisor %></td>
        <td><%= link_to 'Edit', edit_advisor_path(advisor) %></td>
        <td><%= link_to 'Destroy', advisor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advisor', new_advisor_path %>

app/views/advisors/new.html.erb
<h1>New Advisor</h1>

<%= render 'form', advisor: @advisor %>

<%= link_to 'Back', advisors_path %>

app/views/advisors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Advisorid:</strong>
  <%= @advisor.advisorid %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @advisor.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @advisor.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @advisor.email %>
</p>

<p>
  <strong>Student:</strong>
  <%= @advisor.student_id %>
</p>

<%= link_to 'Edit', edit_advisor_path(@advisor) %> |
<%= link_to 'Back', advisors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :csuid %>
    <%= form.number_field :csuid, id: :student_csuid %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :student_firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :student_lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :student_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Csuid</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.csuid %></td>
        <td><%= student.firstname %></td>
        <td><%= student.lastname %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Csuid:</strong>
  <%= @student.csuid %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @student.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @student.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>